<a href="https://colab.research.google.com/github/azhargies/CV/blob/CV/Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# scalar value
a = [100,23]
print(a[0:1])

[100]


In [ ]:
# Dictionaries
# it is have data as key-value pair

d1 = {"Brand":"Audi", "Color":"Black","Speed":200, "Milage":10}
print(d1)
print(type(d1))

{'Brand': 'Audi', 'Color': 'Black', 'Speed': 200, 'Milage': 10}
<class 'dict'>


In [ ]:
# dictionaries are unordered

d1 = {"Brand":"Audi",
      "Color":"Black",
      "Speed":200,
      "Milage":10}
d1["Brand"]

'Audi'

In [ ]:
# Mutable
d1 = {"Brand":"Audi",
      "Color":"Black",
      "Speed":200,
      "Milage":10}
d1["Brand"] = "Mercedes"
print(d1)


{'Brand': 'Mercedes', 'Color': 'Black', 'Speed': 200, 'Milage': 10}


In [ ]:
# Functions in Python
# 1. Built-in Functions, print
# 2. User Defined

In [ ]:
# Function Defn
# Function call



In [ ]:
# y = a*x + b
a = 10
b = 20
# Function Defn
def fn(x):
  y = a*x + b
  return x,y

x1,y1 = fn(10)
print(x1)

10


In [ ]:
def fn(b,c=0,d=0):
  a = b+c+d
  return a,b,c,d

print(fn(10,1))

(11, 10, 1, 0)


In [ ]:
def fn(b,c=0,d=0):
  a = b+c+d
  return a,b,c,d

print(fn(d=10,c=5,b=1))

(16, 1, 5, 10)


In [ ]:
# Lamda function
# single expression
# syntax--> lambda arguments: expression

# f = 9/5 * c + 32

F = lambda c=10: 9/5 * c + 32

F(20)

68.0

In [ ]:
# Modules
import time
print("Welcome to Kohli")
time.sleep(5)
print("Welcom to Jeff Bezos")
time.sleep(5)
print("Welcome to Samanta")

Welcome to Kohli
Welcom to Jeff Bezos
Welcome to Samanta


In [ ]:
import math
a = 25
b = math.sqrt(a)
b

5.0

In [ ]:
import math as m

data = [12,13,14,15]
m.prod(data)

# calculate the product of all elements

32760

In [ ]:
import numpy as np

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

In [ ]:
import numpy as np
a = [1,2,3,4]
n1 = np.array(a)
print(n1)
type(n1)

[1 2 3 4]


numpy.ndarray

In [ ]:
# a + b
a=[1,2,3,4]
b=[4,3,2,1]
a+b

[1, 2, 3, 4, 4, 3, 2, 1]

In [ ]:
# a + b
a=[1,2,3,4]
b=[4,3,2,1]
n1 = np.array(a)
n2 = np.array(b)
n1+n2

array([5, 5, 5, 5])

In [ ]:
import numpy as np
a=[1,2,3,4]
n1 = np.array(a)
print(n1.ndim)
print(n1.shape)

1
(4,)


In [ ]:
L2 = [
       [1,2,3],
       [11,12,13],
       [21,22,23],
       [31,32,33]
     ]
n2 = np.array(L2)
print(n2)
print(n2.ndim)
print(n2.shape)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
2
(4, 3)


In [ ]:
import numpy as np
a=[1,2,3,4]
n1 = np.array(a, dtype="float")
print(n1.dtype)
n1

float64


array([1., 2., 3., 4.])

In [ ]:
import numpy as np
n3 = np.arange(0,10,0.5)
n3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
n4 = np.linspace(0,10,4)
n4

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
rm = np.random.random((2,2))
rm

array([[0.77176941, 0.79587433],
       [0.50213335, 0.1283298 ]])

In [ ]:
ri = np.random.randint(0,10,(3,3))
print(ri)

[[6 5 7]
 [8 5 2]
 [2 5 0]]


In [ ]:
import numpy as np
a = np.random.randint(0,10,(3,2))
b = np.random.randint(0,10,(2,3))
print(a)
print(b)
np.matmul(a,b)

[[8 1]
 [3 7]
 [1 9]]
[[9 3 2]
 [4 0 5]]


array([[76, 24, 21],
       [55,  9, 41],
       [45,  3, 47]])

In [ ]:
import pandas as pd

s1 = pd.Series(data=[12,14,15,13],
               index = ["A","B","C","D"],
               dtype = float)
s1

A    12.0
B    14.0
C    15.0
D    13.0
dtype: float64

In [ ]:
import pandas as pd
a=[[1,2],[3,4]]
df =pd.DataFrame(a,
                 columns=["Col1","Col2"])
df

Col1  Col2
0     1     2
1     3     4

In [ ]:
"""
Name   USN   Score   Result
John   1sj   400     PASS
chethan 028  100     FAIL
Bhavana 023  500     PASS
"""
data = [
    ["John","1sj",400, "PASS"],
   ["chethan", "028",  100 ,    "FAIL"],
  ["Bhavana", "023",  500 ,    "PASS"]
        ]
st_df = pd.DataFrame(data,
                  columns = ["Name" ,  "USN",   "Score",   "Result"])
st_df


Name  USN  Score Result
0     John  1sj    400   PASS
1  chethan  028    100   FAIL
2  Bhavana  023    500   PASS

In [ ]:
st_df.shape

(3, 4)

In [ ]:
st_df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
st_df.columns

Index(['Name', 'USN', 'Score', 'Result'], dtype='object')

In [ ]:
import pandas as pd

pd.read_csv()